# Generated by Django 3.2.8 on 2021-10-13 08:16

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPasswords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', django_cryptography.fields.encrypt(models.CharField(max_length=256))),
            ],
        ),
    ]
