# Generated by Django 3.2.8 on 2021-10-13 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('password_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpasswords',
            name='category',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='userpasswords',
            name='uid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='auth.user'),
            preserve_default=False,
        ),
    ]
