# Generated by Django 3.2.8 on 2021-10-14 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('password_manager', '0002_auto_20211013_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpasswords',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now()),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SharedPasswords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_perm', models.BooleanField(default=False)),
                ('edit_perm', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('password', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='password_manager.userpasswords')),
                ('shared_with_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared', to=settings.AUTH_USER_MODEL)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
