# Generated by Django 3.2.8 on 2021-10-14 06:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('password_manager', '0003_auto_20211014_0639'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SharedPasswords',
            new_name='SharedPasswordsDetails',
        ),
    ]
